<?php
$z[0]=Array("item","",4,85);
$z[0][4]['name']="参考文档";
$z[0][4]['link']="http://help.dedecms.com";
$z[0][4]['rank']="";
$z[0][4]['target']="_blank";
$z[1]=Array("item","",89,176);
$z[1][4]['name']="推荐主机商";
$z[1][4]['link']="http://www.dedecms.com/idc/";
$z[1][4]['rank']="";
$z[1][4]['target']="_blank";
$z[2]=Array("item","",180,264);
$z[2][4]['name']="官方交流论坛";
$z[2][4]['link']="http://bbs.dedecms.com";
$z[2][4]['rank']="";
$z[2][4]['target']="_blank";

?>