<?php
$z[0]=Array("global","",751,776);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",838,863);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",921,946);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",977,1003);
$z[3][4]['name']="cfg_dataurl";
$z[4]=Array("global","",1118,1145);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",1215,1242);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",1245,1271);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",1396,1423);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",1435,1467);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1514,1540);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("global","",2154,2179);
$z[10][4]['name']="cfg_cmsurl";
$z[11]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",2217,2460);
$z[11][4]['type']="top";
$z[11][4]['row']="10";
$z[11][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[12]=Array("tag","\r\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",3922,4052);
$z[12][4]['row']="10";
$z[12][4]['getall']="1";
$z[12][4]['sort']="month";

?>