<?php  exit();
/*
Page: /admin/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/list.php?tid=2
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /admin/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
<?php  exit();
/*
Page: /plus/list.php?tid=2
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
*/
?>
